name: Build
on:
  workflow_call:
  push:
    branches-ignore:
      - main
jobs:
  generate-docs:
    name: Build docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.19']
        node_version: ["lts/*"]
    steps:
      - uses: actions/checkout@v4
      - name: Use golang ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - name: Go version
        run: go version
      - name: generate api reference
        run: ./scripts/api-reference/reference-docs-gen-config.sh
      - name: Use node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: check spell
        run: npm run spellcheck
      - name: create adopters
        run: node ./scripts/adopters/adopters-to-table.js
      - name: Build website
        run: npm run build
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: build-website-${{ github.sha }}-${{ github.run_id }}
